/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_8 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (alufn)
      6'h00: begin
        out = a + b;
      end
      6'h01: begin
        out = a - b;
      end
      6'h33: begin
        out = {15'h0000, (a == b)};
      end
      6'h16: begin
        out = a ^ b;
      end
      6'h20: begin
        out = a << b;
      end
      default: begin
        out = 16'h0000;
      end
    endcase
  end
endmodule
