/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     DUP = 0
     SPLIT = 1
     NOTES = 8
*/
module sig_selector_18 (
    input [15:0] value,
    output reg [15:0] double,
    output reg [7:0] even,
    output reg [7:0] odd
  );
  
  localparam DUP = 1'h0;
  localparam SPLIT = 1'h1;
  localparam NOTES = 4'h8;
  
  
  integer note;
  
  always @* begin
    double = 16'h0000;
    even = 8'h00;
    odd = 8'h00;
    if (1'h0) begin
      for (note = 1'h0; note < 4'h8; note = note + 1) begin
        double[(2'h2 * note)*1+0-:1] = value[(note)*1+0-:1];
        double[(2'h2 * note + 1'h1)*1+0-:1] = value[(note)*1+0-:1];
      end
    end
    if (1'h1) begin
      for (note = 1'h0; note < 4'h8; note = note + 1) begin
        even[(note)*1+0-:1] = value[(2'h2 * (4'h8 - note - 1'h1))*1+0-:1];
        odd[(note)*1+0-:1] = value[(2'h2 * (4'h8 - note) - 1'h1)*1+0-:1];
      end
    end
  end
endmodule
